apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: home-lab-pipeline
spec:
  description: | 
    This pipeline clones a git repo, then echoes the README file to the stdout.
  params:
  - name: repo-url
    type: string
    description: The git repo URL to clone from.

  workspaces:
    - name: shared-data

  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
      - name: output
        workspace: shared-data
      params:
      - name: url
        value: $(params.repo-url)
    - name: install-charts
      workspaces:
        - name: shared-data # <- mapping workspace name
      taskSpec:
        steps:
        - image: praqma/helmsman
          script: ./install.sh