apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: wildcard-le-prod
spec:
  acme:
    email: dorkmeisterx69@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: wildcard-le-prod
    solvers:
    - selector:
        dnsZones:
          - "andrewpjackson.com"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z02810593VHHVZMM6XK6N
          accessKeyID: AKIAVOVK2GSNHIK3LPLS
          secretAccessKeySecretRef:
            name: route53-secret
            key: secret-access-key
          role: arn:aws:iam::375094129818:role/route53-cert-manager-andrewpjackson.com-role
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: andrewpjackson.com
spec:
  secretName: andrewpjackson.com-tls
  issuerRef: 
    kind: ClusterIssuer
    name: wildcard-le-prod
  commonName: "*.andrewpjackson.com"
  dnsNames:
    - "*.andrewpjackson.com"