apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: dorkmeisterx69@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
          - "andrewpjackson.com"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z02810593VHHVZMM6XK6N
          accessKeyID: AKIAVOVK2GSNHIK3LPLS
          secretAccessKeySecretRef:
            name: route53-secret
            key: secret-access-key
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: andrewpjackson.com
spec:
  secretName: andrewpjackson.com-tls
  issuerRef: 
    kind: Issuer
    name: letsencrypt-prod
  commonName: "*.andrewpjackson.com"
  dnsNames:
    - "*.andrewpjackson.com"